### PR TITLE
fix the customer  parameter building of array type  in  body

### PR DESCRIPTION
**Pull request by CrazyBBer**
as talking in : #18

### CODE REVIEW

**Comment by CrazyBBer** [comment]
as talked in : https://github.com/emicklei/go-restful-openapi/issues/18

**Comment by emicklei** [comment]
can you create a unit test for this?

**Comment by CrazyBBer** [comment]
@emicklei UT created https://github.com/emicklei/go-restful-openapi/pull/38/commits/0320a1c551614f05562b0031e8d4b64dbc3e4c02

**Comment by emicklei** [comment]
thank you for contributing

**Pull request merged**
