### PR TITLE
Issue77 , handle [][]byte

### PR DESCRIPTION
**Pull request by emicklei**

### CODE REVIEW

**Comment by SVilgelm** [comment]
I tested this PR

in case of simple `GroupBy [][]string` it creates a incorrect swagger
but if I use extra `type StringArray []string; GroupBy []StringArray` then it generates correct swagger and puts the `StringArray` into definitions

**Comment by emicklei** [comment]
@SVilgelm thanks for checking. I will revisit the change and add more test cases

**Comment by SVilgelm** [comment]
May I ask you to merge this PR and bump a new version?
It partially fixes my issue and I would be really glad to update my very outdated (`v1.1.1`) dependency

**Comment by SVilgelm** [comment]
sorry, seems your path works fine. I just tested again and no issues

**Comment by SVilgelm** [comment]
Here is a log:
```shell
go run github.com/go-swagger/go-swagger/cmd/swagger validate /var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.1aVAEvN0
2021/11/20 21:56:01 
The swagger spec at "/var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.1aVAEvN0" showed up some valid but possibly unwanted constructs.
2021/11/20 21:56:01 See warnings below:
...

The swagger spec at "/var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.1aVAEvN0" is invalid against swagger specification 2.0.
See errors below:
- some references could not be resolved in spec. First found: object has no key
...
exit 1
```

after checkout to this branch:
```shell
go get github.com/emicklei/go-restful-openapi/v2@issue77
...
go run github.com/go-swagger/go-swagger/cmd/swagger validate /var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.GkNv4o4b
2021/11/20 21:57:13 
The swagger spec at "/var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.GkNv4o4b" is valid against swagger specification 2.0
2021/11/20 21:57:13 
The swagger spec at "/var/folders/9r/3x61nl0j7sbb8flp95mx_k400000gn/T/tmp.GkNv4o4b" showed up some valid but possibly unwanted constructs.
2021/11/20 21:57:13 See warnings below:
...
+ exit 0
```

it generate a lot of warnings, but that is another issue, will create a bug report, just need to figure out minimal code to reproduce an issue

**Pull request merged**
