### PR TITLE
Update build_path.go

### PR DESCRIPTION
**Pull request by skyhit**

### CODE REVIEW

**Comment by emicklei** [comment]
can you provide some issue comment here to explain what you are trying to solve/achieve?

**Comment by skyhit** [comment]
@emicklei for example, 

1. for response, I am returning golang type, `map[string]string`, or `map[string]CustomType`
2. for I am returning a custom type like `type CustomStringArray []string`

**Comment by emicklei** [comment]
ic, thank you for given some examples. I kindly ask you to create unit test for these cases.

**Comment by skyhit** [comment]
@emicklei yeah, I will

**Comment by emicklei** [comment]
please update this PR with the latest changes and add any missing unit tests so I can merge it

**Comment by emicklei** [comment]
this PR clearly needs unit tests so we can verify what it actually solves

**Comment by emicklei** [comment]
please check your issues against the current master and fix this PR if you think it sill needs to solve your issue. 
Close if no longer applicable.

**Comment by skyhit** [comment]
@emicklei sure, I saw the changes, I will evaluate locally

**Comment by emicklei** [comment]
any need or progress on this?

**Comment by skyhit** [comment]
@emicklei sorry, I will take a future look, but I see you updated a lot. I will first, test your 1.0.0 release.

**Pull request closed without merging**
