### PR TITLE
handle anonymous struct model

### PR DESCRIPTION
**Pull request by microyahoo**
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

### CODE REVIEW

**Comment by microyahoo** [comment]
Hi @emicklei PTAL, if there is no problem with this pr, please help to do a new tag after merge, thanks.

**Comment by emicklei** [comment]
hi , thank you for your contribution. Can you add a test for this?

**Comment by microyahoo** [comment]
> hi , thank you for your contribution. Can you add a test for this?

Done. PTAL, thanks.

**Comment by microyahoo** [comment]
Hi @emicklei, There is still a problem with my change, which will cause the request deserialization to fail

client code:
```
package smdclient                                                                                   
                                                                                                    
type RoutesCreateOsUserRequestParams struct {                                                       
     RoutesCreateOsUserRequestParamsOsUser *RoutesCreateOsUserRequestParamsOsUser `json:"routes.CreateOsUserRequestParams.os_user"`
} 
```
server code:
```
type CreateOsUserRequestParams struct {                                                                 
    OsUser struct {                                                                                     
        ObjectStoreID         uint   `json:"object_store_id"`                                                                                
        Name                  string `json:"name"`                                                      
        UserName              string `json:"user_name"`                                                 
        BucketQuotaMaxBuckets int32  `json:"bucket_quota_max_buckets"`                                  
        BucketQuotaMaxObjects int64  `json:"bucket_quota_max_objects"`                                  
        BucketQuotaMaxSize    string `json:"bucket_quota_max_size"`                                     
        UserCapability        string `json:"user_capability"`     //default: "*", options: "read", "write", or "read,write"    
        BucketCapability      string `json:"bucket_capability"`   //default: "*", options: "read", "write", or "read,write"    
        MetadataCapability    string `json:"metadata_capability"` //default: "*", options: "read", "write", or "read,write"    
        UsageCapability       string `json:"usage_capability"`    //default: "*", options: "read", "write", or "read,write"    
        ZoneCapability        string `json:"zone_capability"`     //default: "*", options: "read", "write", or "read,write"    
    } `json:"os_user"`                                                                                  
}
```
`restful.Request.ReadEntity()` will fail to decode. Any comment is welcome, thanks.

**Comment by emicklei** [comment]
will have a look later, probably tomorrow

**Comment by emicklei** [comment]
what does the JSON look like?

**Comment by emicklei** [comment]
and how is you change affecting request deserialization? The openapi packages is not part of request processing. So maybe the client is not correctly defining (generating?) the structure.

**Comment by microyahoo** [comment]
Hi @emicklei, sorry for late response.
Suppose there is an anonymous struct as shown below that needs to generate openapi swagger.json file.
```go
type CreateOsUserRequestParams struct {                                                                 
    OsUser struct {                                                                                     
        ObjectStoreID         uint   `json:"object_store_id"`                                                                                
        Name                  string `json:"name"`                                                      
        UserName              string `json:"user_name"`                                                 
        BucketQuotaMaxBuckets int32  `json:"bucket_quota_max_buckets"`                                  
        BucketQuotaMaxObjects int64  `json:"bucket_quota_max_objects"`                                  
        BucketQuotaMaxSize    string `json:"bucket_quota_max_size"`   
    } `json:"os_user"`                                                                                  
}
```
Before I modified, the generated json file was like this
```
  ".os_user": {
   "required": [
    "object_store_id",
    "name",
    "user_name",
    "bucket_quota_max_buckets",
    "bucket_quota_max_objects",
    "bucket_quota_max_size",
   ],
```
The anonymous struct will add model name after my changes, even if the anonymous struct has the same name, it will not be affected.
```
 ".routes.CreateOsUserRequestParams.os_user": {  // <= here
   "required": [
    "object_store_id",
    "name",
    "user_name",
    "bucket_quota_max_buckets",
    "bucket_quota_max_objects",
    "bucket_quota_max_size",
   ],
```
then, I use this swagger.json to generate client code, which will cause the request deserialization to fail. Because the struct json tag is `routes.CreateOsUserRequestParams.os_user`, not `os_user`.
```
type RoutesCreateOsUserRequestParams struct {                                                       
     RoutesCreateOsUserRequestParamsOsUser *RoutesCreateOsUserRequestParamsOsUser `json:"routes.CreateOsUserRequestParams.os_user"`
} 
```

**Pull request closed without merging**
